### PR TITLE
features for each peripheral

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by therealprof** [comment]
Looks good to me. Any other opinions, maybe @Emilgardis?

**Comment by Emilgardis** [comment]
should we maybe play nice and provide a summary feature? i.e `all-peripherals` and `all-groups`

**Comment by burrbull** [comment]
> should we maybe play nice and provide summary features? i.e `all-peripherals` and `all-groups`

Done

**Review by Emilgardis — APPROVED** [review]
bors r=therealprof,emilgardis

looks good :)

**Pull request merged**
