### PR TITLE
Introduce a logging system.

### PR DESCRIPTION
**Pull request by achan1989**
This pull request makes progress on #183.

I've replaced the existing print/eprint calls with the appropriate logging macros, and arbitrarily chose env_logger to handle the logging.

This should be functionally identical to the branch point, although the format of the logging output is different -- it's now of the form `<SEVERITY> svd2rust: <message>`.

### CODE REVIEW

**Comment by ryankurte** [comment]
bors try

**Comment by achan1989** [comment]
I think that might be an issue in the `cortex-m-rt` crate, introduced between versions 0.6.3 and 0.6.4?  [This](https://travis-ci.org/rust-embedded/svd2rust/jobs/430259381) older build managed to compile cortex-m-rt 0.6.3

**Comment by ryankurte** [comment]
Hmm, it does look like it is somewhere there, I'm unfortunately not knowledgeable enough about macros to fix it, but I think I've tracked down the problem. Also, thanks for opening the PR!

Travis Error when running `TRAVIS_OS_NAME=linux TARGET=x86_64-unknown-linux-gnu VENDOR=Nordic ci/script.sh`:
```
error[E0432]: unresolved import `macros::entry`
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rt-0.6.4/src/lib.rs:397:18
    |
397 | pub use macros::{entry, exception, pre_init};
    |                  ^^^^^ no `entry` in the root
error[E0432]: unresolved import `macros::exception`
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rt-0.6.4/src/lib.rs:397:25
    |
397 | pub use macros::{entry, exception, pre_init};
    |                         ^^^^^^^^^ no `exception` in the root
error[E0432]: unresolved import `macros::pre_init`
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rt-0.6.4/src/lib.rs:397:36
    |
397 | pub use macros::{entry, exception, pre_init};
    |                                    ^^^^^^^^ no `pre_init` in the root
error: aborting due to 3 previous errors
```

[cortex-m-rt#L391](https://github.com/rust-embedded/cortex-m-rt/blob/24cb97188d7f93f12e6171b545369a7f8739e4d9/src/lib.rs#L391):
``` rust
extern crate cortex_m_rt_macros as macros;
...
pub use macros::{entry, exception, pre_init};
```

I have reproduced the issue on my machine using `TARGET=x86_64-apple-darwin VENDOR=Nordic TRAVIS_OS_NAME=osx bash ci/script.sh` building with `cargo 1.29.0 (524a578d7 2018-08-05)` and confirmed to be using the packages `cortex-m-rt v0.6.4` and `cortex-m-rt-macros v0.1.2` as in the failed test.

The issue does not seem occur with `cargo 1.29.0-nightly (6a7672ef5 2018-08-14)` or newer, it seems to me that the changes to [cortex-m v0.6.4](https://github.com/rust-embedded/cortex-m-rt/commit/a2bef20e80ba925e3a266141fe404c5ba96b1033) requires newer language features.

@japaric does this seem like a reasonable conclusion / do you have any suggestions on how to fix it?

**Comment by japaric** [comment]
`TRAVIS_OS_NAME=linux TARGET=x86_64-unknown-linux-gnu VENDOR=Nordic sh ci/script.sh` works fine for me on this PR after rebasing, both on stable and nightly.

**Comment by mathk** [comment]
bors try

**Comment by mathk** [comment]
@achan1989 can you do a rebase/merge? Thanks

**Comment by therealprof** [comment]
@achan1989 Sorry for the long delay. Are you still interested in this? If so would you please update the PR?

**Comment by achan1989** [comment]
Oops.  It's been a while, but I'll try to update.

**Comment by achan1989** [comment]
bors try

**Comment by ryankurte** [comment]
bors try

**Pull request merged**
