### PR TITLE
Switch from Travis-CI to GHA

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by adamgreig** [comment]
Huh, what did we have a GitLab CI file for?

bors try

**Comment by therealprof** [comment]
No idea. Seems James has introduced it in early 2018.

**Comment by adamgreig** [comment]
@jamesmunns / @Emilgardis any idea what the GitLab CI file was for?

**Comment by jamesmunns** [comment]
@adamgreig a while ago I ran svd2rust_regress on my gitlab instance, which mirrored the GitHub repo. It's not needed anymore.

**Comment by adamgreig** [comment]
Thanks for confirming!

bors merge

**Pull request merged**
