### PR TITLE
reexport features

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by Emilgardis** [comment]
why haven't we already done this? :3

**Comment by adamgreig** [comment]
> why haven't we already done this? :3

Right now, the PACs must re-export the `interrupt` macro, but we hope to make this not required soon by changing how the macro works in cortex-m-rt. Re-exporting core peripherals was never required though, so making this optional helps reduce external dependencies - the hope is to make it so PACs don't depend on cortex-m or cortex-m-rt at all.

**Comment by burrbull** [comment]
@Emilgardis next one, please

**Review by Emilgardis — APPROVED** [review]

**Comment by Emilgardis** [comment]
docs might need to be updated also

**Pull request merged**
