### PR TITLE
const fn

### PR DESCRIPTION
**Pull request by burrbull**
cc @kossnikita Test `ArrayProxy` yet one time, please.

### CODE REVIEW

**Comment by kossnikita** [comment]
Could you merge this PRs for testing?

**Comment by kossnikita** [comment]
Looks good to me
In my working project, the firmware became 1% smaller 😄

**Comment by burrbull** [comment]
> In my working project, the firmware became 1% smaller 😄

is it with `--release` or without?

**Comment by kossnikita** [comment]
> is it with `--release` or without?

Unfortunately without. There is no difference in release.

**Pull request merged**
