### PR TITLE
test patched STM32

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by therealprof** [comment]
Excuse my ignorance but what are those pached files?

**Comment by adamgreig** [comment]
They're the patched SVDs from stm32-rs (in other words, with all the stm32-rs fixes applied, instead of the raw buggy ST SVDs). Looks like it downloads the current build output from the master branch.

**Comment by burrbull** [comment]
cc @Emilgardis

**Review by Emilgardis — APPROVED** [review]
bors r+

**Pull request merged**
