### PR TITLE
Fixed some trivial clippy lints

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by hannobraun** [comment]
I wonder if I can do this:
bors r=ryankurte

**Comment by hannobraun** [comment]
No, I can't. Somone from @rust-embedded/tools has to merge this :)

**Comment by ryankurte** [comment]
bors r

**Comment by ryankurte** [comment]
oops.

bors r+

**Comment by therealprof** [comment]
bors retry

**Comment by therealprof** [comment]
@rust-embedded/tools @rust-embedded/resources Anyone have an idea why most of the x86 builds are failing?

**Comment by therealprof** [comment]
bors retry

**Comment by therealprof** [comment]
bors try

**Comment by ryankurte** [comment]
Looks like there are a couple of things to fix for nightly?

```
error: lint `private_no_mangle_statics` has been removed: `no longer an warning, #[no_mangle] statics always exported`
```
```
error[E0432]: unresolved import `interrupt`
```

**Comment by therealprof** [comment]
@ryankurte Should be fixed with #244.

**Comment by therealprof** [comment]
bors retry

**Comment by therealprof** [comment]
bors r=ryankurte

**Comment by therealprof** [comment]
Travis build successful, merging manually.

**Pull request merged**
