### PR TITLE
Fix register & cluster derive

### LINKED ISSUE #361: Support derivedFrom when target is register array
#357

### PR DESCRIPTION
**Pull request by burrbull**
Instead of #545 
Closes #361

### CODE REVIEW

**Comment by Emilgardis** [comment]
@robamu does this work well for you?

**Comment by robamu** [comment]
Yes, I already tested it, the generated code remains the same

**Comment by burrbull** [comment]
cc @Emilgardis

**Review by Emilgardis — APPROVED** [review]
bors r+

**Comment by Emilgardis** [comment]
can we add an svd to test this behaviour?

**Pull request merged**
