### PR TITLE
Add missing release tags links

### PR DESCRIPTION
**Pull request by therealprof**
... also changed https://github.com/japaric -> https://github.com/rust-embedded

### CODE REVIEW

**Comment by ryankurte** [comment]
bots r+

**Comment by mathk** [comment]
bors try

**Comment by mathk** [comment]
@ryankurte  I guess there is a typo in your comment.

**Comment by therealprof** [comment]
bors r=ryankurte

**Comment by mathk** [comment]
@therealprof Thanks I just learn a command ;)

**Comment by ryankurte** [comment]
> bots r+

whoops 😅

CI error on nightly:
```
error: failed to run custom build command for `svd2rust v0.14.0 (/project)`
process didn't exit successfully: `/target/debug/build/svd2rust-c4fd4d7869ba4206/build-script-build` (exit code: 1)
--- stderr
/target/debug/build/svd2rust-c4fd4d7869ba4206/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by /target/debug/build/svd2rust-c4fd4d7869ba4206/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: build failed
The command "bash ci/script.sh" exited with 101.
```

**Pull request merged**
