### PR TITLE
Arbitrary Return Types for Register Modification Closures

### PR DESCRIPTION
**Pull request by AdinAck**
Discussed in #859.

## Added
- `write_and`
- `write_with_zero_and`
- `modify_and`

These functions return a `T`. The writer cannot be returned outside of the closure because the lifetime is constrained to remain within the function body.

## Motivation

My reasons for this change are to allow strong type-state validity:

```rust
let state = rb.reg().write_and(|w| State::set(w.field()));
```

Thanks @burrbull!

### CODE REVIEW

**Comment by burrbull** [comment]
> These functions return a `T`

Return a **generic** `T` which corresponds to type returned by passed closure.

Just a note.

**Comment by burrbull** [comment]
Instead of suffix it can be prefix.

What about `external_write`? `ext_write`

**Comment by AdinAck** [comment]
Hey great minds think alike, I was just thinking the same thing.

I was thinking `from_write` (but that's a bit close to `From`) and `with_write`.

**Comment by burrbull** [comment]
`from_write` sounds good

**Comment by AdinAck** [comment]
Ok well I guess we can tentatively go with `from_*` then. Thanks!

**Comment by AdinAck** [comment]
On a side note, to reduce duplicate code, I *think* the original methods could invoke the new ones with the generic T filled in. Will look into it later.

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
cc @Emilgardis any comments?

**Comment by Emilgardis** [comment]
Would it make sense to pit this behind a setting? I think not, but somethibg to maybe consider

**Pull request merged**
