### PR TITLE
Adjust CI to test MSRV and allow nightly to fail

### PR DESCRIPTION
**Pull request by therealprof**
We're now documenting an (arbitrarily chosen) MSRV of 1.37.0 and testing
it in CI while also making nightly tests informational only.

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
bors try

**Comment by burrbull** [comment]
We can merge #381, are we?

**Comment by burrbull** [comment]
LGTM

**Comment by therealprof** [comment]
@burrbull Yes, that's the plan. ;)

**Pull request merged**
