### PR TITLE
feat: Add keep_list arg to allow not to generate arrays

### PR DESCRIPTION
**Pull request by duskmoon314**
## New feature

Add a `keep_list` arg to allow not to generate arrays.

```shell
svd2rust --help
# --keep_list        Keep lists when generating code of dimElement, instead of trying to generate arrays

svd2rust --target riscv --keep_list -i soc.svd
```

Use `[%s]` to create arrays and use `%s` to create lists

ref: https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_special.html

## Motivation

Issue #561

Might be useful if someone needs lists.

### CODE REVIEW

**Comment by burrbull** [comment]
Need to check how it interact with #354 when `--const_generic` is enabled and complex dim indexes are present.

**Comment by burrbull** [comment]
Rebase, please.

**Comment by duskmoon314** [comment]
> Rebase, please. And rustfmt

rebase and fmt done

**Review by burrbull — APPROVED** [review]

**Pull request merged**
