### PR TITLE
release 0.33.5

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Review by jannic — APPROVED** [review]

**Comment by burrbull** [comment]
@jannic looks lile you are not in https://github.com/orgs/rust-embedded/teams/tools

**Comment by jannic** [comment]
> @jannic looks like you are not in https://github.com/orgs/rust-embedded/teams/tools

I know. Different team. Still I looked through the PR and think it's fine, so I added my approval.
If the number of people in the tools team is becoming a bottleneck and my help is appreciated, I could of course join the team. I won't have much time to do actual development, but could help with reviews and occasional bugfixes.

**Comment by burrbull** [comment]
cc @Emilgardis

**Comment by burrbull** [comment]
@Emilgardis I need your approve.

**Review by Emilgardis — APPROVED** [review]

**Pull request merged**
