### PR TITLE
type aliases in RegisterBlock

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
After this PR I'm planning to make release. So need more tests.
cc @newAM  @duskmoon314 @luojia65 
Still not sure about #636

**Review by Emilgardis — APPROVED** [review]

**Review by newAM — APPROVED** [review]
Works for me, on target tests pass: https://github.com/stm32-rs/stm32wlxx-hal/runs/7547539890?check_suite_focus=true

if anyone else is using nix you can drop into a with this version:

```bash
nix develop github:newAM/nix-shells/svd2rust-pr645#stm32-rs
```

**Comment by duskmoon314** [comment]
LGFM at the first glance

I noticed that in the generated code, the code order of many of the register fields changed. Is this intentional? (Though this doesn't infect anything. I'm just curious.)

**Review by duskmoon314 — APPROVED** [review]

**Comment by luojia65** [comment]
Looks good on my projects, it would make register block definition clear, so LGTM.

**Review by luojia65 — APPROVED** [review]

**Comment by burrbull** [comment]
> I noticed that in the generated code, the code order of many of the register fields changed. Is this intentional? (Though this doesn't infect anything. I'm just curious.)

The cause should be that fields now sorted by bit offset

**Comment by burrbull** [comment]
bors r=@Emilgardis

**Pull request merged**
