### PR TITLE
offset-in-proxy

### PR DESCRIPTION
**Pull request by burrbull**
@therealprof 

Can you tests this change. It adds offset into proxy structure according #115 and can reduce code size in some cases.
It's interesting how debug builds react on this.

### CODE REVIEW

**Comment by burrbull** [comment]
r? @therealprof 

изображение

**Comment by therealprof** [comment]
Sure, I'll give it a shot.

**Comment by therealprof** [comment]
Increases code size on dev builds usually by around 10 percent, no change on release builds.

**Comment by burrbull** [comment]
So we have to wait const generics for third part from https://github.com/rust-embedded/svd2rust/pull/331#issue-300628516

**Comment by therealprof** [comment]
Have you tried factoring the bits function into a generic bits function, à la:
```
fn bits_u32 (self, value: u32, field: u32, mask: u32, offset: usize) -> u32 {
    value &= !(mask << offset);
    value |= ((field as u32) & mask) << offset;
    value
}
```
and calling that instead?

**Comment by burrbull** [comment]
I don't see how this can help.

**Comment by therealprof** [comment]
Well, we're trying to find a solution for two different problems:

1. For dev builds we need to have the least amount of code because it won't be optimised away under any circumstance; huge amounts of could and also repetitive code are very bad here
2. For release builds we're interested in having code which the compiler can properly optimise; repetitive code doesn't matter but if we get rid of it it must be done in a way that the compiler can still see how to get rid of it again

**Comment by burrbull** [comment]
I agree with the goals.  It is easy to implement generic code for readers as they don't have feedback with registers, but it’s harder for writers.
Field writers produce register writers and have different offsets.

**Pull request closed without merging**
