### PR TITLE
Simplistic check if FPU is defined in CPU-block

### PR DESCRIPTION
**Pull request by AfoHT**
Working with a LPC1347 board, compilation fails with 

```
 pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU};
                                                           ^^^ no `FPU` in `peripheral`. Did you mean to use `MPU`?
```
The [SVD file](https://github.com/ax-rwnd/rust-lpc1347/blob/master/LPC13Uxx_patched.svd) provides the information that no FPU (nor MPU) is present.

### CODE REVIEW

**Comment by jamesmunns** [comment]
Looks reasonable to me!

bors try

**Comment by therealprof** [comment]
@AfoHT Looks like something went wrong here. Can you please rebase against the current master?

**Comment by AfoHT** [comment]
Hope that solved that unfortunate push to master

**Comment by therealprof** [comment]
bors retry

**Comment by jamesmunns** [comment]
Build Passed, merging manually

**Pull request merged**
