### PR TITLE
Use TokenStreams directly instead of Vec<TokenStream>

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
I'm trying to do add some rework on the final TokenStream and having `Vec<TokenStream>` is a complication I'd rather not have. The produced output is identical for me but as a bonus I'm seeing a nice consistent 5% processing speedup.

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
To mitigate CI troubles by having errors at the in a potentially Megabytes long line I added line breaks at the end of any `]`. And while doing so I figured out that dumping the `TokenString` into a `String` and writing the data all at once speeds up the whole thing the whole process by a factor of ten(!).

**Comment by therealprof** [comment]
LOL, and of course I just noticed a typo in my change. Let's say if the build finished, otherwise I'm going to fix it before the next go.

**Comment by burrbull** [comment]
bors try

**Comment by therealprof** [comment]
bors r=burrbull

**Pull request merged**
