### PR TITLE
Remove useless `Variant`, use Option instead

### PR DESCRIPTION
**Pull request by burrbull**
As each  `FieldReader` now has `bits` method, I think it is not an issue.

### CODE REVIEW

**Comment by burrbull** [comment]
See #496

**Review by therealprof — DISMISSED** [review]
Using `Option` makes a lot of sense and lets us profit from upstream optimisations and methods which is a good thing. Would you mind removing the `u8` change from this PR so we can get that merged?

**Comment by burrbull** [comment]
> Using `Option` makes a lot of sense and lets us profit from upstream optimisations and methods which is a good thing. Would you mind removing the `u8` change from this PR so we can get that merged?

Done.

**Review by adamgreig — APPROVED** [review]
bors merge

**Comment by adamgreig** [comment]
bors merge

**Pull request merged**
