### PR TITLE
support for alternateGroup registers

### PR DESCRIPTION
**Pull request by burrbull**
See #504

### CODE REVIEW

**Review by therealprof — COMMENTED** [review]
Looks good to me in general. Where is this needed?

**Comment by burrbull** [comment]
> Looks good to me in general. Where is this needed?

Some vendors (like Atmel, or Freescale) use `alternateGroup` to specify registers with that can use different set of fields in different modes.
I've just added this group name as prefix for register name. So now there are no conflicts.

**Comment by burrbull** [comment]
cc @adamgreig  @john-terrell

**Review by therealprof — APPROVED** [review]
LGTM

bors r+

**Pull request merged**
