### PR TITLE
simplify enum derive

### PR DESCRIPTION
**Pull request by burrbull**
r? @therealprof 

IMPORTANT. Requires [Rust 1.37](https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#referring-to-enum-variants-through-type-aliases)

### CODE REVIEW

**Comment by therealprof** [comment]
> IMPORTANT. Requires Rust 1.37

I don't think bumping the MSRV is acceptable. At the very least this would require a discussion and vote.

**Comment by burrbull** [comment]
I know. It is low priority PR. Add do-not-merge if you can.

**Comment by burrbull** [comment]
bors try

**Comment by burrbull** [comment]
bors try

**Comment by burrbull** [comment]
bors try

**Pull request merged**
