### PR TITLE
Mips target

### PR DESCRIPTION
**Pull request by kiffie**
r? @therealprof 

Hi all,

Willing to add some basic support for MIPS cores? This patch enables the Peripheral Singleton. I use svd2rust to create PACs for PIC32MX microcontroller.

Best regards,

Stephan

### CODE REVIEW

**Comment by burrbull** [comment]
Add test if it is possible and update changelog, please.

**Comment by Emilgardis** [comment]
if possible, add some [svd2rust-regress](https://github.com/rust-embedded/svd2rust/tree/6bfc843f7fb8d5ea91e85fdc04d6c37e4dda63fb/ci/svd2rust-regress) targets as well, not necessary but appreciated.

**Comment by kiffie** [comment]
```svd2rust-regress```target added.

```CHANGELOG.md``` updated

Reviewing all the code motivated me to move the core access stuff to a new crate ```mips_mcu``` to separate it from the startup routine and the ISR tables. I changed my svd2rust patch accordingly.

**Comment by burrbull** [comment]
Here also, please:
https://github.com/rust-embedded/svd2rust/blob/master/ci/script.sh

**Comment by kiffie** [comment]
> Here also, please:
> https://github.com/rust-embedded/svd2rust/blob/master/ci/script.sh

done.

**Comment by burrbull** [comment]
Update this line and squash commits:
https://github.com/rust-embedded/svd2rust/blob/6bfc843f7fb8d5ea91e85fdc04d6c37e4dda63fb/.github/workflows/ci.yml#L17

**Comment by burrbull** [comment]
Looks good to me

**Comment by kiffie** [comment]
> Looks good to me

Yes, the tests passed. In the meantime, I created PACs that include ```Peripherals::take()```.

Would be great if you could merge it.

**Comment by burrbull** [comment]
I still wait you squash commits.

**Comment by kiffie** [comment]
I didn't realize that there was still an open point because I was not familiar with "squashing" commits. Now everything should be in one single commit.

**Review by burrbull — APPROVED** [review]

**Comment by kiffie** [comment]
Cool. @burrbull, thanks a lot for your help and patience.

**Pull request merged**
