### PR TITLE
Fix generated code for MSP430 atomics

### PR DESCRIPTION
**Pull request by YuhanLiin**
Rebased from #685

### CODE REVIEW

**Comment by burrbull** [comment]
SVD link 404 error

**Review by burrbull — APPROVED** [review]

**Comment by YuhanLiin** [comment]
Note: Now that I've switched the atomic library over to `portable-atomic`, we might be able to port this feature over to other targets.

**Comment by burrbull** [comment]
> Note: Now that I've switched the atomic library over to `portable-atomic`, we might be able to port this feature over to other targets.

it sounds interesting

**Comment by adamgreig** [comment]
I haven't compared them in detail, but for other targets it might make more sense to use [`atomic-polyfill`](https://crates.io/crates/atomic-polyfill) which builds on `critical-section` and is quite widely used in other embedded Rust projects. `portable-atomic` can only use a global disable-interrupts to simulate CAS operations (when enabled with `--cfg portable_atomic_unsafe_assume_single_core`), while `atomic-polyfill` uses `critical-section` which allows pluggable implementations (and is used in svd2rust for `Peripherals::take()`).

At the moment I don't think `atomic-polyfill` supports MSP430 at all, so it's not an option here (yet?).

**Pull request merged**
