### PR TITLE
Xtensa updates

### PR DESCRIPTION
**Pull request by MabezDev**
* Switch to bare-metal 1.0.0
* Use xtensa-lx `InterruptNumber` trait
* Update CI script

### CODE REVIEW

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
Changelog, please.

**Comment by MabezDev** [comment]
Done :)

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
bors merge

**Comment by adamgreig** [comment]
Ah, it looks like `bitflags` has been updated from 1.2.1 to 1.3.1 due to `xml-rs` requiring `^1.0`, but [bitflags 1.3.1](https://github.com/bitflags/bitflags/blob/main/CHANGELOG.md#130-yanked) uses some const fns that bump the effective MSRV.

Now the MSRV is 1.46.0; @MabezDev maybe you could update the MSRV in this PR? Need to change `.github/workflows/ci.yaml`, `.github/bors.toml`, and `README.md`.

**Review by adamgreig — APPROVED** [review]
Thanks, let's give it a go.

bors r+

**Pull request merged**
