### PR TITLE
Address build failures on nightly due to lint

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
After a lot of massaging due to additional problems retrieving the docker containers those two changes will bring `svd2rust` CI back to life.

r? @rust-embedded/tools

**Comment by jamesmunns** [comment]
bors r+
(we'll see if this works, I asked to be added to bors perms)

**Comment by therealprof** [comment]
bors retry

**Comment by japaric** [comment]
Travis build was green. Merging manually.

**Pull request merged**
