### PR TITLE
Add ESP32 support

### PR DESCRIPTION
**Pull request by arjanmels**
Adding support for ESP32 as used in new pull requests on https://github.com/esp-rs.

ESP32 has 2 level interrupt handling. First level in the cores. Second level in the periphery/software.

### CODE REVIEW

**Comment by burrbull** [comment]
can you add any tests for esp32?

**Comment by arjanmels** [comment]
Ok, will look into it, but will be next week.

**Comment by arjanmels** [comment]
@burrbull @therealprof Thanks for the lightning fast review!

**Comment by therealprof** [comment]
bors ping

**Comment by therealprof** [comment]
bors retry

**Comment by burrbull** [comment]
with new `svd-parser`:
[ERROR svd2rust] In device Espressif

Caused by:
    0: In peripheral `AES`
    1: Peripheral have `registers` tag, but it is empty

`registers` tag can't be empty according to https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html

**Comment by arjanmels** [comment]
@burrbull, @mabezdev Ok, I will look into fixing teh example svd, hopefully later today, but cannot promise.

**Comment by arjanmels** [comment]
@burrbull I updated the svd file, so now should be ok. (I tested it with branch svd_new, but it also passed before the updates, so I might have done something wrong.)

**Pull request merged**
