### PR TITLE
array-proxy for disjoint arrays

### LINKED ISSUE #748: Implement disjoint array
#660 

Is it possible to add an unsafe method that returns a register from an array? For compatibility with similar syntax for continuous arrays.

In my case the registers are separated due to their size. And I can't use them with indexes anymore.

```xml
<register>
  <dim>4</dim>
  <dimIncrement>0x4</dimIncrement>
  <dimIndex>1-4</dimIndex>
  <name>C%sDT</name>
  <displayName>C1DT</displayName>
  <description>Channel data register</description>
  <addressOffset>0x34</addressOffset>
  <size>0x10</size>
  <access>read-write</access>
  <resetValue>0x00000000</resetValue>
  <writeConstraint>
    <range>
      <minimum>0</minimum>
      <maximum>65535</maximum>
    </range>
  </writeConstraint>
</register>
```

```rust
#[doc = "0x34 - Channel data register"]
pub c1dt: CDT,
_reserved14: [u8; 0x02],
#[doc = "0x38 - Channel data register"]
pub c2dt: CDT,
_reserved15: [u8; 0x02],
#[doc = "0x3c - Channel data register"]
pub c3dt: CDT,
_reserved16: [u8; 0x02],
#[doc = "0x40 - Channel data register"]
pub c4dt: CDT,
_reserved17: [u8; 0x02],
```

I'd like to see something like this

```rust
impl RegisterBlock {
    #[doc = "0x34..0x44 - Channel data register"]
    #[inline(always)]
    pub const unsafe fn cdt(&self, n: u8) -> &CDT {
        &*(self as *const Self)
            .cast::<u8>()
            .add(52usize + 4usize * (n - 1))
            .cast()
    }
}
```

### PR DESCRIPTION
**Pull request by burrbull**
fixes #748
cc @kossnikita

### CODE REVIEW

**Comment by kossnikita** [comment]
Did I miss something?

```rust
error[E0277]: `generic::ArrayProxy<generic::Reg<tmr1::cdt::CDT_SPEC>, 4, 4>` doesn't implement `Debug`
  --> src\tmr1.rs:34:5
   |
3  | #[derive(Debug)]
   |          ----- in this derive macro expansion
...
34 |     pub cdt: crate::ArrayProxy<CDT, 4, 0x04>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `generic::ArrayProxy<generic::Reg<tmr1::cdt::CDT_SPEC>, 4, 4>` cannot be formatted using `{:?}`
```

**Comment by burrbull** [comment]
Try again.

**Comment by burrbull** [comment]
@n8tlarsen Could you test if nothing broken?

**Comment by kossnikita** [comment]
Works good in my case

**Review by therealprof — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
