### PR TITLE
Edition-2018-ify svd2rust

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by mathk** [comment]
Ping from triage: #282 is now merge.

**Comment by mathk** [comment]
TAuthor need to rebase/merge

**Comment by Disasm** [comment]
Ping from triage: @therealprof, could you rebase your changes?

**Comment by therealprof** [comment]
bors try

**Comment by mathk** [comment]
Ping from triage @therealprof bors is still failing is that expected?

**Comment by mathk** [comment]
bors try

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
@rust-embedded/tools Can I get a r+?

**Comment by japaric** [comment]
(@Disasm GH notifications are [currently down](https://www.githubstatus.com/) so bors is not working either)

**Comment by therealprof** [comment]
@Disasm @japaric Also I'm afraid Disasm is not a member of the right team, but maybe they'd like to be? 😅

**Comment by Disasm** [comment]
@therealprof I definitely want to make some tools and improve `svd2rust`, but I doubt I will be able to handle all of these. I already hardly have time to do PR triage :disappointed:

**Pull request merged**
