### PR TITLE
One enum

### PR DESCRIPTION
**Pull request by burrbull**
r? @therealprof

### CODE REVIEW

**Comment by therealprof** [comment]
Weird, again I see absolutely not change in the generated files for my test SVDs (except for the `_{}W`-> `{}_W` change that is). It strikes me odd that some large SVD files are not even exercising the code you're changing...

**Comment by therealprof** [comment]
bors try

**Comment by burrbull** [comment]
It just can not be.

**Comment by therealprof** [comment]
Well, it is... I reverted `{}_W` line from your PR just so I am able to see trees in the forrest but after that change the diff is completely empty. I'm using the upstream `STM32F042x.svd` for my tests, BTW. Because then I can actually see the compiled code and sizes...

**Comment by burrbull** [comment]
Does your SVD contain <enumeratedValues>?
Try https://stm32.agg.io/rs/stm32f0x2.svd.patched

**Comment by therealprof** [comment]
I can certainly try other SVD files. Two problems here: I cannot test my code base against patches versions and we do not have test cases on the CI based on those, so if only patched SVDs exercise those features we're basically not testing those which is bad...

**Comment by burrbull** [comment]
I think this is record.
изображение

Previous time:
изображение

**Comment by therealprof** [comment]
Not really, CI times vary quite a bit. We had similar "quick" builds e.g. here: https://travis-ci.org/rust-embedded/svd2rust/builds/564713886

**Comment by burrbull** [comment]
So is here something blocking merge?
Do you want I revert "{}_W" or something else?

**Comment by therealprof** [comment]
Well, as I said. I can't see any changes with my set-up infrastructure and I'd definitely like to be sure that this is tested, preferably in CI. So either someone can tell me which currently tested SVD file exercises this change or this will need to wait until I switch my tests to use the `stm32-rs` svd file.

**Comment by burrbull** [comment]
cc @adamgreig 
cc @Disasm

**Comment by Disasm** [comment]
Well, seems like the svd2rust output is unable to build on stable.
```
error: enum variants on type aliases are experimental
  --> src/aes/tag_in_flag.rs:75:22
   |
75 |         self.variant(TAG_IN_FLAG_A::CAN_INPUT)
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^
```
Checked on this repo: https://github.com/riscv-rust/k210-pac

**Comment by therealprof** [comment]
Oh, have I mentioned that we definitely should have SVD files in CI which exercise all code in a PR. 🙄

Well probably have to revert the variant changes and work on modernising CI a bit so this doesn't happen again.

**Comment by Disasm** [comment]
Hmm, why `VENDOR=OTHER` is checked only on nightly?

**Comment by burrbull** [comment]
@Disasm I forgot to try on stable. I've reverted. Can you try again.

**Comment by Disasm** [comment]
@burrbull Checked, the error is still here.

**Comment by burrbull** [comment]
Try again, please. Now it should be fixed.

**Comment by Disasm** [comment]
Now it builds. On k210-pac it shows 6.3% build time reduction compared to master. Not bad!

**Comment by therealprof** [comment]
@Disasm Since it seems to be buildable on stable, would you be willing to move RISC-V out of the OTHER category and make it testable on stable in a new PR?

**Comment by Disasm** [comment]
@therealprof Yep, working on this.

**Comment by therealprof** [comment]
@burrbull Would you rebase please?

**Comment by burrbull** [comment]
Done.

**Comment by burrbull** [comment]
It's funny:
https://github.com/rust-lang/rust/pull/61682

The problem that was blocking compilation on stable will not be in 1.37.

**Pull request merged**
