### PR TITLE
implement Debug for Field/BitReader + generic Debug for Reg

### PR DESCRIPTION
**Pull request by burrbull**
addition for #836

### CODE REVIEW

**Comment by burrbull** [comment]
cc @Emilgardis

**Comment by burrbull** [comment]
Let's land this first.

**Comment by Emilgardis** [comment]
```
/ci diff pr --current " --impl-debug"
```

**Comment by burrbull** [comment]
> ```
> /ci diff pr --current " --impl-debug"
> ```

Ok. Unsderstood.
But how to enable a flag for both `before` and `after` state?

**Comment by Emilgardis** [comment]
for both it's just
```
#/ci diff pr -- --impl-debug
```

**Review by Emilgardis — APPROVED** [review]

**Pull request merged**
