### PR TITLE
add missing defmt impls

### LINKED ISSUE #880: TryFromInterruptError doesn't derive Format when defmt is enabled

### PR DESCRIPTION
**Pull request by burrbull**
Fixes #880 

cc @MabezDev @romancardenas @Emilgardis

### CODE REVIEW

**Review by Emilgardis — DISMISSED** [review]

**Comment by burrbull** [comment]
@Emilgardis rebased

**Review by romancardenas — APPROVED** [review]
LGTM

**Review by MabezDev — APPROVED** [review]
Thanks! Sorry I didn't get a chance to make the PR myself :sweat_smile:

**Comment by burrbull** [comment]
@Emilgardis need to update approve.

**Review by Emilgardis — APPROVED** [review]

**Pull request merged**
